### ISSUE TITLE
ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by piotrekm7** [piotrekm7/Polynomial#20]
Dla wielomianu x^3+1 program się wysypuje. Problemem jest w MenuScreen, a konkretnie linijka 109:
_x[i-z] = new Label(pisz, new Label.LabelStyle(sofiaProSoftMedium46px, Color.BLACK));
x[i-z].setPosition(190 * w + layout.width / 2 + 100, upY(h * 75 + 150));_
W pewnym momencie i=1 z=2.
Proszę o wprowadzenie poprawki.

**Comment by MikszaM** [comment]
Wsadziłem to wszystko do:
if(z<=i){

}
I działa dla tego przykładu. Mam nadzieje że dla innych też
